### ISSUE TITLE
Some characters are displaying like square on Russian and other problems

### ISSUE THREAD

**Issue by dimon7147** [Ponzel/InfraSpaceLocalization#2]
![image](https://user-images.githubusercontent.com/20266345/122282730-6a8e8800-cef4-11eb-93de-02009cb2bf61.png)
![image](https://user-images.githubusercontent.com/20266345/122282780-78440d80-cef4-11eb-80fc-791f4aad528a.png)
![image](https://user-images.githubusercontent.com/20266345/122283069-d40e9680-cef4-11eb-895c-1941a74feeb9.png)
![image](https://user-images.githubusercontent.com/20266345/122283376-23ed5d80-cef5-11eb-9c50-7e8d74e82e1d.png)
![image](https://user-images.githubusercontent.com/20266345/122283510-4aab9400-cef5-11eb-9999-9bc2580942aa.png)
Power poles connection tutorial are on English and there is no possible to translate it.
And with each game reload, the places where these squares appear are different.

**Comment by Ponzel** [comment]
Fixed it all and I'm currently uploading the update :)
