### ISSUE TITLE
german translation, some english recommendations

### ISSUE THREAD

**Issue by Pingg05** [Ponzel/InfraSpaceLocalization#50]
Betonfabrik => Betonwerk
Hausgerät => Haushaltsgerät
Luftfilteranlage(Air filter facility) => Atmosphärenprozessor
Düngeranlage => Düngerfabrik
Motorfabrik => Motorenfabrik or Motorenwerk (BMW = Bayrische Motorenwerke)

Dieses Spiel ist noch nicht fertig. Es könnte Bugs beinhalten\n\nWir veröffentliche diese frühen Versionen an Spieler damit wir Feedback zum Gameplay erhalten und Bugs finden können lange bevor das Spiel offiziell veröffentlicht wird. => .......Bugs finden können, lange bevor....

Das Spiel wurde seit %minutes% Minuten nicht gespeichert. Bist du sicher, dass du ohne zu speichern zum Hauptmenü gehen willst? => .......zum Hauptmenü zurückkehren willst?

Unzulässige Buchstaben im Dateinamen => Unzulässige Zeichen im Dateinamen

Dateiname schon verwendet => Dateiname schon vorhanden
Tutorials Zurücksetzen => Tutorials zurücksetzen
Rotieren => Drehen
Straße herabsenken => Straße absenken
Links rotieren => nach links drehen
Rechts rotieren => nach rechts drehen
Öffne Ordner mit Bildschirmfotos => Ordner der Bildschirmfotos öffnen = Bildschirmfoto-Ordner öffnen
"Spielversion ändern " => "Spielversion ändern"

Keine Roadmap gefunden.\n\nHast du Verbindung zum Internet? => Keine Roadmap gefunden.\n\nHast du eine funktionierende Internetverbindung?

Du hast es nicht geschafft, dich um deine Bürger zu kümmern. Deine Stadt wurde zurückgestuft bist du ihre Bedürfnisse wieder erfüllen kannst. => Du hast es nicht geschafft dich um deine Bürger zu kümmern. Deine Stadt wurde zurückgestuft bis du ihre Bedürfnisse wieder erfüllen kannst.

_the building name is Windkraftanlage, therefore this should be Windkraftanlage too_

Verwirbelungen senken Windradeffizienz => Verwirbelungen senken die Effizienz der Windkraftanlagen
Zwei Windräder stehen zu nah zusammen. Ihre Effizienz ist reduziert. => Zwei Windkraftanlagen stehen zu nah zusammen. Ihre Effizienz ist reduziert.

Kiesstraße => Schotterstraße
Solarzellen => Solarpanele

Erweitere dein Stromnetz durch Umspannwerke, sodass du nicht mehr jedes Gebäude mit Strommästen versorgen musst. => ......Strommasten....

Große Bagger => Große Schaufelradbagger
Selbstreinigende Solarzellen => Selbstreinigende Solarpanele
Eingehendes Lager leer => Eingangslager leer 
Kein Anschluss zur Straße => Keine Straßenanbindung
Ausgehendes Lager voll => Ausgangslager voll
Diese Technologie schaltet frei: => Diese Technologie ermöglicht:

Oxygen Processor => oxygen capture plant
Sauerstofffilteranlage => Sauerstoffabscheidungsanlage

Carbon Processor => carbon capture plant
Kohlenstofffilteranlage =>Kohlenstoffabscheidungsanlage

in front of every "greek" is a space to much

**Comment by watchakorn-18k** [comment]
you try contact Ponzel#9737 in discord to solve this problem
