### ISSUE TITLE
websit steam.md

### ISSUE THREAD

**Issue by namidasechi** [Ponzel/InfraSpaceLocalization#9]
# Short Description
### English
InfraSpace is a sci-fi city builder - but every resource you produce has to go through your transport infrastructure. In order to thrive in this solar system, you'll not only have to start mining operations and manage production chains, but also make sure your road network is up to the task.

I check steam description.
A sci-fi city builder where the flow of resoueces goes through your city's transport infrastructure.Build an extrasolar effciency utopia from nothing.Start mining operations,plan production,and lay down transportation routes to ensure a smooth supply chain.

The description is different, but which one should I translate?

**Comment by Ponzel** [comment]
The second one is the newer one! I'll update Steam.md with the new version as well.
